default_platform(:ios)

platform :ios do

  desc "Create a new app on AppStoreConnect"
  lane :register do
    produce(
      username: "gaapalharesapple@gmail.com",
      app_identifier: "palhares.RickAppMorty",
      app_name: "RickAppMorty"
    )
  end

end