default_platform(:ios)

platform :ios do

  lane :register_app do
    produce(app_name: "RickAppMorty")
  end

  lane :get_dev_certs do
    cert(development: true)
    sigh(development: true)
  end

  lane :sync_all_development do
    match(type: "development")
  end

  lane :sync_device_info do
    register_devices(
      devices: {
        "Palhares iPhone" => "c34ba7b8415e1f7da32195985642a929b19151b5"
      }
    )
  end

end